{
 "title": "PegaSys+",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Recent Blocks Proposed By Node",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "plus_poa_recently_proposed_block_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Recent Blocks Signed By Node",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "plus_poa_ibft_recent_signed_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IBFT Rounds for Latest Block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "plus_poa_ibft_rounds_for_latest_block",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block Validator Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "plus_poa_validator_count_current",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IBFT Unique Recent Signers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "plus_poa_ibft_unique_recent_signers",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Recent Proposer Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "targets": [
    { "expr": "plus_poa_recent_proposer_count", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}